[package]
name = "diar"
version = "0.1.0"
edition = "2018"

[dependencies]
byteorder = "1.4.3"
fs2 = "0.4.3"
memmap2 = "0.3.0"
mime_guess = "2.0.3"
thiserror = "1.0.26"
tree_magic_mini = { version = "3.0.0", features = ["tree_magic_db"] }
zstd = "0.9.0"
