[package]
name = "diar"
version = "0.1.0"
edition = "2018"

[dependencies]
byteorder = "1.4"
fs2 = "0.4"
jwalk = "0.6"
memmap2 = "0.3"
mime_guess = "2.0"
rayon = "1.5"
thiserror = "1.0"
tracing = "0.1"
tree_magic_mini = { version = "3.0", features = ["tree_magic_db"] }
zstd = "0.9"

[dev-dependencies]
tracing-subscriber = "0.2"

[profile.dev]
opt-level = 2
lto = false

[profile.release]
opt-level = 3
debug = 1
lto = true
